model_parameters:
    name : 'NVDM'
    encoder :
        name : 'PTFCEncoder'
        input_dim : 20000
        hidden_dim : 1000
        latent_dim : 10
        architecture : 'NVDM'
    decoder :
        name : 'PTFCDecoder'
        latent_dim : 10
        output_dim : 20000
        batch_size : 500
        architecture : 'NVDM'


experiment_parameters:
  name : 'PTVAEXperiment'
  seed : 50
  dataset : beer
  data_path : 'resources/datasets/beer'
  sparse: True
  labels: True
  save_path : 'results'
  batch_size : 500
  learning_rate : 5e-5
  use_cuda : True


trainer_parameters:
  max_epochs : 1000
  patience : 50 # used for early stopping , ignored if set to 0 - also depends on test_interval
  log_interval : 10 # log every 10th batch
  test_interval : 1  # evaluate on test(valid) every epoch
  track:
    loss_components: False # track and log all components of the loss
    perplexity: False


