model_parameters:
    name : 'HFVAE'
    encoder :
        name : 'HFCEncoder'
        input_dim : 2000
        hidden_dim : 500
        latent_dim : 50
        num_groups : 2
        architecture : 'NVDM'
    decoder :
        name : 'HFCDecoder'
        latent_dim : 50
        output_dim : 2000
        batch_size : 500
        num_groups : 2
        architecture : 'NVDM'
    beta: (4.0, 1.0, 1.0, 7.0, 0.0) # template (gamma, 1, alpha, beta, 0.0)
    num_samples: 1

experiment_parameters:
  seed : 50
  name : 'HFVAE_7_4'
  dataset : 20news
  data_path : 'resources/datasets/20news'
  save_path : 'results'
  batch_size : 500
  max_epochs : 1000
  learning_rate : 5e-5
  use_cuda : True



